### ISSUE TITLE
The static web app build fails with error message 'Failed to add static_web_app_url to step outputs.'

### ISSUE THREAD

**Issue by ABL6COB** [Azure/static-web-apps#1006]
**Describe the bug**

The static webapp deploy build is failing with the error message "Failed to add static_web_app_url to step outputs." after the deployment is completed.

The deployment is completed but build fails as like below.
Status: Succeeded. Time: 45.1245672(s)
Deployment Complete :)
Visit your site at: https://<staticsiteurl>.azurestaticapps.net/
Failed to add static_web_app_url to step outputs.

**To Reproduce**
The build fails each time we trigger it.

**Expected behavior**
The build should not fail with error message "Failed to add static_web_app_url to step outputs."

**Screenshots**

**Device info (if applicable):**

**Additional context**

**Comment by annikel** [comment]
Hi @ABL6COB, would you mind sharing more details about your site like your default hostname or the deployment ID. Feel free to create a support ticket if you do not want to share this information here.

**Comment by oliverstreissi** [comment]
We have the same problem, although we made no changes to our deploy script. The deployment succeeds but always throws the same error at the end.

**Comment by annikel** [comment]
@oliverstreissi could you provide a default hostname or deployment ID please?

**Comment by timstarbuck-boystown** [comment]
Also started seeing this recently.

DeploymentId: 98eea244-a33a-4b2c-a706-2da83786286d

Finished Upload. Polling on deployment.
Status: InProgress. Time: 0.1685213(s)
Status: Succeeded. Time: 15.2191648(s)
Deployment Complete :)
Visit your site at: https://white-field-0e998b110.1.azurestaticapps.net/
Failed to add static_web_app_url to step outputs.

**Comment by pdiazdumont** [comment]
Hi, I'm facing the same issue. For more context, I'm deploying the site from a BitBucket pipeline using the following script:
```
- step: &deploy-application
  name: Deploy Application
  image: mcr.microsoft.com/appsvc/staticappsclient:stable
  script:
    - /bin/staticsites/StaticSitesClient upload --verbose --app ./dist --skipAppBuild true --apiToken $AZURE_DEPLOY_TOKEN
```
As mentioned above by other users, the deployment finishes correctly but the status is failed due to this:
`Failed to add static_web_app_url to step outputs.`

**Comment by vivekjilla** [comment]
@timstarbuck-boystown , @pdiazdumont  can you please share your full deployment logs.

@timstarbuck-boystown  are you also facing this on bitbucket

**Comment by vivekjilla** [comment]
Looking at this further, @pdiazdumont can you please try adding `--deploymentProvider 'BitBucket'` in your script command. That should resolve this.

@ABL6COB, @oliverstreissi , @timstarbuck-boystown If you're also hitting into this using custom deployment scripts, can you please try passing the above configuration parameter with appropriate provider value and see if it resolves the issue for you.

or if it's failing on Github Action runs, can you please share more details/logs. Thanks!
Apologies for the inconvenience, and we will work on not failing the run in this scenario.

**Comment by timstarbuck-boystown** [comment]
@vivekjilla Yes, we are currently using BitBucket and verified adding --deploymentProvider 'BitBucket' did fix the issue. 

Thanks!

**Comment by TuukkaLaakso** [comment]
@vivekjilla 
I have it failing with the same error on GitHub Action runs (enterprise GitHub) with a simple workflow:
```
name: Deploy to test

on:
  push:
    branches:
      - test

jobs:
  build_and_deploy_job:
    runs-on: [self-hosted, linux]
    name: Build and Deploy Job
    steps:
      - name: CHOWN dir
        run: sudo chown -R $USER:$USER ${{ github.workspace }}
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_QA }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/build" # App source code path
          api_location: "/api" # Api source code path - optional
          output_location: "" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
```
Error log:
```
Finished Upload. Polling on deployment.
Status: InProgress. Time: 0.1447625(s)
Status: InProgress. Time: 15.2252711(s)
Status: Succeeded. Time: 30.3783657(s)
Deployment Complete :)
Visit your site at: <removed>
Failed to add static_web_app_url to step outputs.

For further information, please visit the Azure Static Web Apps documentation at https://docs.microsoft.com/en-us/azure/static-web-apps/
If you believe this behavior is unexpected, please raise a GitHub issue at https://github.com/azure/static-web-apps/issues/
Exiting
```
So the deployment actually completes OK, the Action just fails in the end.

**Comment by vivekjilla** [comment]
Thanks for highlighting this @TuukkaLaakso . We're working on a fix to not fail the action in the end in these scenarios.

**Comment by ABL6COB** [comment]
Hi @vivekjilla , Any updates here, we are still facing this issue.

**Comment by vivekjilla** [comment]
Hi @ABL6COB we have a fix ready waiting deployment. Should be resolved in couple of weeks. Sorry for the delay.

**Comment by oldking139** [comment]
hi @vivekjilla , we met same problem with Github Enterprise server + self hosted runner (Linux). 

The runner version is: _linux-x64-2.296.2_

we test both Ubuntu 20.04 and Rocky Linux 8.7. (It _**can**_ show the url correctly even it throw the error later.)
![image](https://user-images.githubusercontent.com/45203648/216792992-7b4360c3-a14e-4515-bbb9-f3c5fdb4ae45.png)

the action config is here: https://github.com/VTB-LINK/VTB-STUDIO/actions/runs/3849950721/workflow
We just sync this repo to internal to get a action runner test, without change any thing in action config.

**Comment by vivekjilla** [comment]
@ABL6COB @oldking139 This issue should be resolved now. Please re-open if it's not the case. Thanks!
