### ISSUE TITLE
ISR not working 

### ISSUE THREAD

**Issue by ShadowSonata** [Azure/static-web-apps#1058]
**Describe the bug**

We are creating a website serving static content from CMS and would like to use next.js incremental static regeneration to update the content whenever the CMS gets updated. 
We understand the on-demand revalidation is currently unavailable on SWA so we just intend to do simple ISR by adding `revalidate: 10` to `getStaticProps`. 
However this was not working and the web content never gets updated.

It works on the local machine after build and run `npm start`

**To Reproduce**
Deploy the static web app via default github action.
Update content on CMS.
Refresh the page after the revalidate time.

**Expected behavior**
The static web pages should get updated based on CMS API endpoint.

**Additional context**
* Tested with both free and standard version of static web app and neither of them are working
* Due to the SWA size limitation, the following modifications have to be done at deployment => otherwise it will fail
   * Add this to github action: `api_build_command: 'rm -rf ./node_modules/@next/swc-* ./.next/cache'`
   * Modify `package.json`: `"build": "next build && rm -rf ./.next/cache",`
 
Github action log
 ```
Route (pages)                              Size     First Load JS
┌ ● / (ISR: 10 Seconds) (575 ms)           2.64 kB         107 kB
├   /_app                                  0 B             104 kB
├ ● /[...pid] (ISR: 10 Seconds) (2794 ms)  4.54 kB         109 kB
├   ├ /contact-us (868 ms)
├   ├ /project (657 ms)
├   ├ /assessment (636 ms)
├   └ /reports (633 ms)
└ ○ /404 (493 ms)                          295 B           104 kB
+ First Load JS shared by all              167 kB
  ├ chunks/framework-f53495389f0ff39c.js   45.4 kB
  ├ chunks/main-c4f6fe10d0434f14.js        26.3 kB
  ├ chunks/pages/_app-7939c10ca9b363e0.js  27.2 kB
  ├ chunks/webpack-e1f5ed1b0a04dda0.js     5.15 kB
  └ css/a3e51a7b76d974f0.css               63.2 kB

○  (Static)  automatically rendered as static HTML (uses no initial props)
●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
   (ISR)     incremental static regeneration (uses revalidate in getStaticProps)

Preparing output...

Copying files to destination directory '/bin/staticsites/97df41fe-b528-449b-8961-2c81a52fdece-swa-oryx/app'...
Done in 3 sec(s).

Removing existing manifest file
Creating a manifest file...
Manifest file created.
Copying .ostype to manifest output directory.

Done in 87 sec(s).


---End of Oryx build logs---
Finished building app with Oryx
No Api directory specified. Azure Functions will not be created.
Created default file: /bin/staticsites/97df41fe-b528-449b-8961-2c81a52fdece-swa-oryx/app/.next/index.html
Starting to build function app with Oryx
Oryx will build function app with the following custom override command: rm -rf ./node_modules/@next/swc-* ./.next/cache
---Oryx build logs---


```

Workflow file
```
jobs:
  build_and_deploy_job:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LEMON_WAVE_0D01E4500 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: 'upload'
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: '/' # App source code path
          api_location: '' # Api source code path - optional
          output_location: '.next'
          deployment_environment: 'dev'
          #### remove big modules as we are not using server side rendering to create content
          api_build_command: 'rm -rf ./node_modules/@next/swc-* ./.next/cache'
          ###### End of Repository/Build Configurations ######
```

**Comment by vivekjilla** [comment]
@ShadowSonata Can you please check if the content is getting updated after 2*(revalidate time)? 
If so, we're working on a resolution for this issue and should be fixed soon.

**Comment by ShadowSonata** [comment]
> @ShadowSonata Can you please check if the content is getting updated after 2*(revalidate time)? If so, we're working on a resolution for this issue and should be fixed soon. Apologies for the inconvenience.

@vivekjilla Heya thanks for the reply...
It just doesn't get updated at all... Almost feels like the static export deployment.

**Comment by vivekjilla** [comment]
@ShadowSonata Oh, sorry to hear that. Is it possible to share some more details like the site endpoint and the page where the ISR is not working and what's expected, so that we can look into the issue more.

**Comment by vivekjilla** [comment]
@ShadowSonata We also recently deployed few changes where we fixed a bug related to ISR.  Here is a [thread](https://github.com/Azure/static-web-apps/discussions/1066) related to that. Please check it out and let me know if there are any issues.

**Comment by ShadowSonata** [comment]
@vivekjilla Thanks for the reply. Sorry I should have replied to you earlier.

Glad to hear that we have a new version! So I did another check today.

With these new changes, firstly I modified the `next.config.js` to support standalone mode.

For the build process, I tested if I could use the default `next build`... Unfortunately I will still get the app size limit error. So I reverted to `"next build && rm -rf ./.next/cache"`.

On my local machine, I can build it with this and then run `next start` - it works fine.

On static web app, interestingly I get all pages that call `getStaticProps` with 404 error. 
The github action looks fine, it has successfully retrieved the data from backend api (see below)
```
> digital-eis-frontend@0.1.0 build
> next build && rm -rf ./.next/cache

warn  - No build cache found. Please configure build caching for faster rebuilds. Read more: https://nextjs.org/docs/messages/no-cache
Attention: Next.js now collects completely anonymous telemetry regarding usage.
This information is used to shape Next.js' roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://nextjs.org/telemetry

info  - Linting and checking validity of types...
info  - Creating an optimized production build...
info  - Compiled successfully
info  - Collecting page data...
info  - Generating static pages (0/7)
info  - Generating static pages (1/7)
info  - Generating static pages (3/7)
info  - Generating static pages (5/7)
info  - Generating static pages (7/7)
info  - Finalizing page optimization...

Route (pages)                              Size     First Load JS
┌ ● / (539 ms)                             1.34 kB         106 kB
├   /_app                                  0 B             105 kB
├ ● /[...pid] (ISR: 10 Seconds) (3203 ms)  16.6 kB         122 kB
├   └ css/179f95589e0c8391.css             119 B
├   ├ /contact-us (919 ms)
├   ├ /assessment (915 ms)
├   ├ /project (685 ms)
├   └ /documents (684 ms)
└ ○ /404 (399 ms)                          2.38 kB         107 kB
+ First Load JS shared by all              168 kB
  ├ chunks/framework-f53495389f0ff39c.js   45.4 kB
  ├ chunks/main-c4f6fe10d0434f14.js        26.3 kB
  ├ chunks/pages/_app-1062a760fe61d677.js  28.3 kB
  ├ chunks/webpack-f2efbfbbd3de293e.js     4.83 kB
  └ css/82ffd2ba844901fa.css               63.5 kB

○  (Static)  automatically rendered as static HTML (uses no initial props)
●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
   (ISR)     incremental static regeneration (uses revalidate in getStaticProps)

Preparing output...

Copying files to destination directory '/bin/staticsites/9e8bd10a-b6ea-4a3a-b5f5-a3ba0f74a27e-swa-oryx/app'...
Done in 3 sec(s).

Removing existing manifest file
Creating a manifest file...
Manifest file created.
Copying .ostype to manifest output directory.

Done in 81 sec(s).


---End of Oryx build logs---
Finished building app with Oryx
Detected standalone folder, so using it for deployment.
Repackaged Next.js app to deploy on the backend function.
Skipping step to build /bin/staticsites/9e8bd10a-b6ea-4a3a-b5f5-a3ba0f74a27e-swa-oryx/app/.next/standalone with Oryx
Function Runtime Information. OS: linux, Functions Runtime: ~4, node version: 16
Zipping Api Artifacts
Done Zipping Api Artifacts
Zipping App Artifacts
Done Zipping App Artifacts
Uploading build artifacts.
Finished Upload. Polling on deployment.
Status: InProgress. Time: 0.1725642(s)
Status: InProgress. Time: 15.3427342(s)
Status: Succeeded. Time: 30.5169212(s)
Deployment Complete :)
```

btw I'm using this plugin [next-common-props](https://www.npmjs.com/package/next-common-props) on my next.config.js as well. And the `next.config.js` is like this
```
/** @type {import('next').NextConfig} */
const nextCommonProps = require('next-common-props')
const nextConfig = {
  reactStrictMode: true,
  images: {
    unoptimized: true,
  },
  output: 'standalone',
}

module.exports = nextCommonProps(nextConfig)
```


Could this be an issue?



With all the frustrations at the moment with static web app, we actually have moved away from SWA and decide to use container app instead. I can use all features from `next.js` like on-demand revalidation. But we still hope the issues from static web app could be resolved.

Thanks for your help.

**Comment by vivekjilla** [comment]
Thanks for trying out @ShadowSonata and sharing the feedback. 

Sorry to hear your scenario is not working as expected. I would like to understand more on what's going on here. 

Is it possible to share your site details where you are seeing 404, so that we can figure out what's going wrong. 

Also `next build` should just work ideally as cache folder won't get created in standalone folder. Can you also please share your workflow.yml if possible.

TIA!

**Comment by ShadowSonata** [comment]
Hi @vivekjilla

Please see GitHub action below
```
jobs:
  build_and_deploy_job:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        env:
          API_TOKEN: ${{ secrets.STRAPI_API_TOKEN }}
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LEMON_WAVE_0D01E4500 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: 'upload'
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: '/' # App source code path
          api_location: '' # Api source code path - optional
          output_location: '.next'
          deployment_environment: 'new-swa'
```

This was what happened when I used the plain `next build` without removing the cache folder.
```
Detected standalone folder, so using it for deployment.
Repackaged Next.js app to deploy on the backend function.
Skipping step to build /bin/staticsites/f5e2c6dd-0268-4501-abdc-4e77f1256950-swa-oryx/app/.next/standalone with Oryx
Function Runtime Information. OS: linux, Functions Runtime: ~4, node version: 16
Zipping Api Artifacts
Done Zipping Api Artifacts
The content server has rejected the request with: BadRequest
Reason: The size of the app content was too large. The limit for this Static Web App is 262[144](https://github.com/arup-group/digital-eis-frontend/actions/runs/4141602040/jobs/7161361114#step:4:145)000 bytes. For a higher app size limit, consider upgrading to the Standard plan.

For further information, please visit the Azure Static Web Apps documentation at https://docs.microsoft.com/en-us/azure/static-web-apps/
If you believe this behavior is unexpected, please raise a GitHub issue at https://github.com/azure/static-web-apps/issues/
Exiting
```

For the deployed pages, you might check this [link](https://lemon-wave-0d01e4500-newswa.eastasia.2.azurestaticapps.net/project) but I don't think that might be super useful. All those pages reverted back to 404 page are using `getStaticProps` and set `revalidate: 10`.

**Comment by vivekjilla** [comment]
Thanks for providing more details @ShadowSonata. 

Are you using `fallback: false` in your `getStaticPaths` method for these `hostname/<pageid>` type of paths. 
That could be the reason for ISR not working previously or seeing 404s now.

**Comment by ShadowSonata** [comment]
Hi @vivekjilla 

I did some other testing as you suggested.

1. Revert the build to `"build": "next build"` and keep the standalone setting

This still failed with the same reason (size too large)

2. setting `fallback: true` in `getStaticPaths`

tbh I don't understand why we have to set this value to `true`. With this set to `true`, the application completely crashed (we haven't set the error boundary yet)
<img width="809" alt="image" src="https://user-images.githubusercontent.com/28591411/218608493-4fe46602-1f64-4313-a618-9ada46b782d4.png">

<img width="691" alt="image" src="https://user-images.githubusercontent.com/28591411/218608606-3781d286-6f1c-4061-947b-5b512d580571.png">

It gave me uncaught error on all pages with dynamic routing. For non-dynamic pages it worked fine.

**Comment by ShadowSonata** [comment]
@vivekjilla Thanks for your quick reply... yes it was my fault to forget to load environment variables at run time... I added those to portal and it now works!

Since the ISR issue has been fixed I suppose you can close this now. :)

**Comment by vivekjilla** [comment]
@ShadowSonata Thanks for sharing all the details and helping us in improving the product. Glad the issue is resolved.

**Comment by FrimJo** [comment]
I'm trying to have `export const revalidate = 0` Route Segment Config [Revalidate](revalidate) to work on Static Web App using NextJs App router. But when I set it `0` the page returns "500: Internal Server Error".
