### ISSUE TITLE
.NET 6 Preview 4 & Blazor WASM AOT Compilation

### ISSUE THREAD

**Issue by Zhiyuan-Amos** [Azure/static-web-apps#452]
Hello! When will .NET 6 Preview 4 be supported? Also, will AOT compilation be supported through some sort of configuration? 😄

**Comment by anthonychu** [comment]
This is blocked by: https://github.com/dotnet/sdk/issues/17865

A workaround is to run the build on Windows, like this: https://github.com/anthonychu/ConwayBlazor/blob/3460b8877f05a9bf099e2e473def3f45dc8924fd/.github/workflows/azure-static-web-apps-orange-sky-00add8710.yml

Looks like this will be fixed in Preview 5. Created an issue to see if Oryx can build this automatically when Preview 5 is out. https://github.com/microsoft/Oryx/issues/1026

Also added an issue to track updating Oryx to Preview 4. https://github.com/microsoft/Oryx/issues/1025

/cc @danroth27 @arroyc

**Comment by qianz2** [comment]
@anthonychu We recently supported .NET preview 4, it should be available through dynamic installation now.

**Comment by anthonychu** [comment]
You can now deploy .NET 6 Blazor WebAssembly apps, including those that use AOT, to Azure Static Web Apps! Blazor WebAssembly is automatically detected and the `wasm-tools` workload is automatically installed. See [blog post](https://techcommunity.microsoft.com/t5/apps-on-azure/full-stack-net-6-apps-with-blazor-webassembly-and-azure-static/ba-p/2933428) for more information.

**Comment by loganmarshall1** [comment]
Fantastic this is amazing going to try it out in production right now :)￼

**Comment by loganmarshall1** [comment]
Hi @anthonychu 

Works Great! 1 more question... ;)... Current Azure DevOps message is...

`Oryx has timed out while building app, the current limit is 15 minutes. Failing build.`

AOT'd 154 dlls, is there anyway that I can Opt out of certain dlls from AOT? like ones that take long to help?  

is there a setting in .csproj?  currently my csproj states...

` <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
	<RunAOTCompilation>True</RunAOTCompilation>
  </PropertyGroup>  `

**Comment by anthonychu** [comment]
We've added an [input parameter](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/AzureStaticWebAppV0/task.json#L109) `build_timeout_in_minutes` to the task that should be rolling out during this month. Not sure if it's widely available yet to all DevOps customers.

I don't know if there's a way to opt out of certain DLLs. @danroth27 any ideas here?

**Comment by loganmarshall1** [comment]
Thank you @anthonychu ! will it be a param here: 
![image](https://user-images.githubusercontent.com/19997240/141027400-4ef6643f-f894-49bd-8a54-7ccdfb387973.png)

Hi @danroth47 , long time fan of yours! nice to meet you! wow so happy that I'm on a thread your tagged in! makes me feel like "Waynes World" "Im not worthy" :D. <3 what you do, your positivity and continued smart drive which is helping all developers everywhere!  Please let @anthonychu and I know if there's a csproj 'switch' that exists?  if not, no action needed in my case as the Input Parameter that @anthonychu mentioned should be perfect for this! thanks kindly!

**Comment by danroth27** [comment]
> AOT'd 154 dlls, is there anyway that I can Opt out of certain dlls from AOT? like ones that take long to help?

Not yet. Having a mixture of AOT compiled code and normal assemblies is tricky for the runtime to handle, so for .NET 6 the only supported configuration is to AOT compile everything to WebAssembly.

**Comment by loganmarshall1** [comment]
Hi @danroth27 thanks for your quick reply! 

FYI (Tuesday) we just pushed **7 Blazor wasm PWAs** to Production on **Dotnet 6** and customers are LOVING IT!  They said they noticed "30% speed improvements" EVERYWHERE! :D .  Our apps currently have over Average ~ 10k users per 7 apps.

Currently for the Trimmer I've added this to CSPROJ
`  <ItemGroup>
	 <TrimmerRootAssembly Include="Microsoft.Authentication.WebAssembly.Msal" />
  </ItemGroup>`
  
  Which helped for "trimming unused assemblies" i believe ;) .  Maybe a CSPROJ Switch as all thats needed for a future proof **AOT**?
  
  perhaps, 
  `<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
	<RunAOTCompilation>True</RunAOTCompilation>
	<RunAOTCompilation Exclude="SomeHuge.Big.Maybe.SuperHuge.Dll">False</RunAOTCompilation>
  </PropertyGroup>  `
  
  Oh by the Way, **you and @anthonychu , and everyone else** are doing so great! you inspire tons of DEVs **everyday** and We ALL love you positive, smart, upbeat personality! <3

**Comment by danroth27** [comment]
> FYI (Tuesday) we just pushed 7 Blazor wasm PWAs to Production on Dotnet 6 and customers are LOVING IT! They said they noticed "30% speed improvements" EVERYWHERE! :D . Our apps currently have over Average ~ 10k users per 7 apps.

That's awesome! Great to hear! If you're open to us sharing your story with using .NET & Blazor on our [.NET Customers](https://dot.net/customers) page, you can share your story with us using this [form](https://aka.ms/CustomerShowcaseForm).

> Currently for the Trimmer I've added this to CSPROJ
> `<ItemGroup> <TrimmerRootAssembly Include="Microsoft.Authentication.WebAssembly.Msal" /> </ItemGroup>`
> Which helped for "trimming unused assemblies" i believe ;) .

Doesn't marking Microsoft.Authentication.WebAssembly.Msal as a [root assembly](https://docs.microsoft.com/dotnet/core/deploying/trimming/trimming-options#root-assemblies) mean that it doesn't get trimmed at all? Is that what you intended to do?

**Comment by loganmarshall1** [comment]
Will do! Thanks Dan!!!!

Yes completely intended!
￼apparently it was a workaround needed when .net 6 preview￼ x came out. MSAL Was getting overly trimmed to the point that blazor wasm auth didn't work.  i'm sure I can take this out of the file now since .NET 6 is now GA 😄

￼￼The big thing with CSPROJ file temp fixes Is they kind of "live in there" for years and no one knows whether or not they can take them out. 

Github or a stack overflow fix suggests... ￼"Oh just put this in your CSPROJ" 😅

The great news is that a lot of these fixes work right away 👍￼

I would love to get your feedback on everyone that has put in things in there￼ CSPROJ as 'workarounds', and how do we inform customers on you can take it out now?￼￼￼

I wonder if it's just regular a .net developer email communication that says "hey if you put these things in your Csprojfile before as a temp fix, you don't need to have them in there anymore￼"

even better yet do we have analyzers on ".CSPROJ"? I think I just blew my own mind 😂

analyzer would state "this <item group/> you added currently does absolutely nothing would you like to remove?" 😊￼￼￼￼

perhaps they're just benign and don't affect things. I for one love clean perfect code and I definitely appreciate knowing that everything is ONLY there for a reason. :)

thanks again for your quick response. I keep on getting good feedback about you and everyone on the team!￼￼

**Comment by DaleCam** [comment]
Hi there,
I still have this issue in dot net 8.
When using YAML to publish to Azure Static Web Apps, i get the same error:

Using .NET Core SDK Version: 8.0.100
"2023-12-01 20:14:11"|ERROR|  Determining projects to restore...
/opt/dotnet/8.0.100/sdk/8.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.ImportWorkloads.targets(38,5): error NETSDK1147: To build this project, the following workloads must be installed: wasm-tools [/working_dir/Deckhand.Mobile/Mobile.Pwa/Mobile.Pwa.csproj]
/opt/dotnet/8.0.100/sdk/8.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.ImportWorkloads.targets(38,5): error NETSDK1147: To install these workloads, run the following command: dotnet workload restore [/working_dir/Deckhand.Mobile/Mobile.Pwa/Mobile.Pwa.csproj] | 1 | Please build your app locally before publishing. | https://docs.microsoft.com/en-us/azure/app-service/configure-language-dotnetcore?pivots=platform-linux


---End of Oryx build logs---
Oryx build has completed. Took 32.5293328 seconds. Exit Code: 1
Oryx has failed to build the solution.

The YAML im using:
jobs:
  - job: build_and_deploy_job
    displayName: Build and Deploy Job
    pool:
      vmImage: ubuntu-latest
    variables:
      - group: Azure-Static-Web-Apps-variable-group
    steps:
      - checkout: self
        submodules: true
      - task: AzureStaticWebApp@0
        inputs:
          app_location: 'Mobile/Mobile.Pwa'
          output_location: 'wwwroot'
          api_location: 'Api'
          verbose: true
          build_timeout_in_minutes: 30
          azure_static_web_apps_api_token: '$(AZURE_STATIC_WEB_APPS_API_TOKEN)'

**Comment by thomasgauvin** [comment]
@dalecam we're working on the fix for this for Blazor & .NET 8, keeping the other thread updated https://github.com/Azure/static-web-apps/issues/1334

**Comment by DaleCam** [comment]
@danroth27 - My company is desperately needing AOT for our blazor dotnet 8 App that's being used by about 60,000 users.  Is there any way this issue can be prioritised?

**Comment by danroth27** [comment]
@dalecam WebAssembly AOT should already be supported on Azure Static Web Apps. What issue are you hitting?

@thomasgauvin Should this issue be closed?

**Comment by DaleCam** [comment]
@danroth27 - There is a thread with more information here: 
https://github.com/Azure/static-web-apps/issues/1334#issuecomment-1810463688
It wasn't building with AOT for a few months, however I tried the pipeline again today and its now working! 
So please ignore this! 
Thank you for your prompt reply - much appreciated.
