### ISSUE TITLE
SWA - Failed to deploy the Azure Functions - EnvironmentId tag is set

### ISSUE THREAD

**Issue by johnmccormick99** [Azure/static-web-apps#723]
Seeing an issue when deploying swa with an api using ADO AzureStaticWebApp@0 task

api works fine when running the swa cli emulator locally

Function Runtime Information. OS: windows, Functions Runtime: ~4, dotnet version: 6.0
Finished building function app with Oryx
Zipping Api Artifacts
Done Zipping Api Artifacts
Zipping App Artifacts
Done Zipping App Artifacts
Uploading build artifacts.
Finished Upload. Polling on deployment.
Status: InProgress. Time: 0.1298361(s)
Status: InProgress. Time: 15.981754(s)
Status: InProgress. Time: 31.2706856(s)
Status: Failed. Time: 46.393219(s)
Deployment Failed :(
Deployment Failure Reason: Failed to deploy the Azure Function

I see a similar issue was raised https://github.com/Azure/static-web-apps/issues/622

I have tried changing the api from .net to node/js etc and received the same error. swa is deployed to west europe.

**Comment by miwebst** [comment]
Hi @johnmccormick99 

This looks like an issue on our side, we are looking into it.

**Comment by miwebst** [comment]
Hey @johnmccormick99, 

Looks like we have a bug with how we handle the 'EnvironmentId' tag. Can you try removing this from your SWA?

**Comment by digitalanalogue9** [comment]
@miwebst - I've just hit the same issue - where do I find the EnvironmentId tag (to remove it) please ?

**Comment by miwebst** [comment]
Your deployment failure could be caused by something else (i.e. failure to startup). In this specific incident, an EnvironmentId tag was added to the SWA and caused the issue. Tags can be added/removed in the Overview in the Portal. If you did not add it, it likely does not exist and you are hitting another issue.

**Comment by miwebst** [comment]
Probably best to confirm that your Function is able to startup and function as expected using the Function tools in VS Code.

**Comment by tinys000** [comment]
Hello, 

Same issue for me.
It works in my local environment `npx swa start build --api-location api` but never when I try to deploy it with an AzureStaticWebApp task in my pipeline.
I tried with javascript, typescript and dotnet function but nothing works.

Any 'EnvironmentId' tag set in my side.

---End of Oryx build logs---
Function Runtime Information. OS: windows, Functions Runtime: ~4, dotnet version: 6.0
Finished building function app with Oryx
Zipping Api Artifacts
Done Zipping Api Artifacts
Zipping App Artifacts
Done Zipping App Artifacts
Uploading build artifacts.
Finished Upload. Polling on deployment.
Status: InProgress. Time: 0.1238067(s)
Status: InProgress. Time: 15.2399686(s)
Status: InProgress. Time: 30.4544307(s)
Status: Failed. Time: 45.592686(s)
Deployment Failed :(
Deployment Failure Reason: Failed to deploy the Azure Functions.

**Comment by miwebst** [comment]
I'm going to update the title of this issue and close it as the initial issue around 'EnvironmentId' is rare and likely not relevant to these tests. My advice for debugging this type of issue would be to add application insights and see what logs are emitted when you deploy: https://docs.microsoft.com/en-us/azure/static-web-apps/monitor

**Comment by johnnyreilly** [comment]
We've documented the workaround here: https://blog.johnnyreilly.com/2022/07/07/static-web-apps-failed-to-deploy-the-azure-functions

**Comment by DeepakR-28** [comment]
> We've documented the workaround here: https://blog.johnnyreilly.com/2022/07/07/static-web-apps-failed-to-deploy-the-azure-functions

Hey @johnnyreilly  we don't have any EnvironmentId in our tags, still facing the Azure functions issue. 
Do you know any other reasons, or is it a MS issue?

**Comment by johnnyreilly** [comment]
I'm not sure I'm afraid
